### PUT request to update new patient record
PUT http://localhost:4000/patients/9671e9df-616d-4517-a20d-90dbce5a0a19
Content-Type: application/json

{
  "name": "Adhyan Das",
  "address": "New Address",
  "email": "b@example.com",
  "dateOfBirth": "1998-11-10"
}

###